### ISSUE TITLE
A new release with tensorflow-2.10 ? 

### ISSUE THREAD

**Issue by chaithyagr** [mrphys/tensorflow-mri#34]
Given that there were updates in tensorflow-nufft whose features I would like to use, a new release will surely be helpful which supports tensorflow-2.10 ?

**Comment by jmontalt** [comment]
Certainly! Currently working on that. Hopefully it'll happen this week, but if not it will be next week. In the meantime, note that you can use [TensorFlow NUFFT 0.9.0](https://github.com/mrphys/tensorflow-nufft/releases/tag/v0.9.0), which also includes the features you need and works with TF 2.9.x. The only difference between TensorFlow NUFFT 0.9.0 and 0.10.0 is that it bumps the TF version from 2.9.x to 2.10.x.

**Comment by jmontalt** [comment]
This has been addressed with v0.22.0.
